version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: docker/app.docker
    restart: unless-stopped
    volumes:
      - ./:/var/www
    links:
      - db

  worker:
    build:
      context: .
      dockerfile: docker/worker.docker
    restart: always
    volumes:
      - ./:/var/www
      - ./docker/conf/worker.conf:/etc/supervisor/conf.d/worker.conf
    links:
      - db

  db:
    image: postgres:11.4
    restart: always
    ports:
      - ${DOCKER_DB_PORT}:5432
    volumes:
      - ${DOCKER_DB_DATA}:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}

  web:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./docker/conf/vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${DOCKER_WEB_PORT}:80
    links:
      - app